name: Deploy to VPS Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy to VPS
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
          cd /home/$VPS_USER
          # Clone the latest version of the repository
          git clone https://github.com/khoidang2110/cicd_vps_docker.git nextjs_fe || (cd nextjs_fe && git pull)
          cd nextjs_fe || exit
          # Stop and remove the existing container, if any
          docker stop nextjs_fe_container || true
          docker rm nextjs_fe_container || true
          # Remove the old Docker image
          docker rmi -f nextjs_fe_img || true
          # Build the Docker image
          docker build -t nextjs_fe_img .
          # Run the Docker container
          docker run --restart=always -d -p 4000:3000 --name nextjs_fe_container nextjs_fe_img
          # Clean up by removing the cloned repository files
          cd ..
          rm -rf nextjs_fe
        EOF
