name: Deploy to VPS docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t nextjs_fe_img .

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Create tarball and deploy
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        # Create a temporary directory
        TEMP_DIR=$(mktemp -d)
        # Copy files to the temporary directory
        cp -r . $TEMP_DIR/
        # Create a tarball from the temporary directory
        tar -czf nextjs_fe.tar.gz -C $TEMP_DIR .
        # Clean up temporary directory
        rm -rf $TEMP_DIR
        # Check if tarball is created
        ls -lh nextjs_fe.tar.gz
        # Copy the tarball to the VPS
        scp -o StrictHostKeyChecking=no nextjs_fe.tar.gz $VPS_USER@$VPS_IP:/home/$VPS_USER/
        # SSH into the VPS to extract and deploy
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
          cd /home/$VPS_USER
          # Check if tarball exists
          ls -lh nextjs_fe.tar.gz
          # Create the nextjs_fe directory if it doesn't exist
          mkdir -p nextjs_fe
          # Extract the tarball into the nextjs_fe directory
          tar -xzf nextjs_fe.tar.gz -C nextjs_fe
          cd nextjs_fe || exit
          docker build -t nextjs_fe_img .
          docker stop nextjs_fe_container || true
          docker rm nextjs_fe_container || true
          docker run --restart=always -d -p 4000:3000 --name nextjs_fe_container nextjs_fe_img
          # Remove the old tarball
          rm -f /home/$VPS_USER/nextjs_fe.tar.gz
          # Clean up old deployment
          rm -rf /home/root/nextjs_fe
        EOF
