name: Deploy to VPS Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t nextjs_fe_img .

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Create tarball and deploy
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        # Create a temporary directory
        TEMP_DIR=$(mktemp -d)
        # Sao chép tệp vào thư mục tạm thời
        cp -r . $TEMP_DIR/
        #Tạo tarball từ thư mục tạm thời
        tar -czf nextjs_fe.tar.gz -C $TEMP_DIR .
        # Dọn dẹp thư mục tạm thời
        rm -rf $TEMP_DIR
        # Kiểm tra xem tarball đã được tạo chưa
        ls -lh nextjs_fe.tar.gz
        # Sao chép tarball vào VPS
        scp -o StrictHostKeyChecking=no nextjs_fe.tar.gz $VPS_USER@$VPS_IP:/home/$VPS_USER/
        # SSH vào VPS để giải nén và triển khai
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
          cd /home/$VPS_USER
          # Kiểm tra xem tarball có tồn tại không
          ls -lh nextjs_fe.tar.gz
          # Tạo thư mục nextjs_fe nếu nó không tồn tại
          mkdir -p nextjs_fe
          #Giải nén tarball vào thư mục nextjs_fe
          tar -xzf nextjs_fe.tar.gz -C nextjs_fe
          cd nextjs_fe || exit
          docker build -t nextjs_fe_img .
          docker stop nextjs_fe_container || true
          docker rm nextjs_fe_container || true
          docker run --restart=always -d -p 4000:3000 --name nextjs_fe_container nextjs_fe_img
          # Xóa tarball cũ
          rm -f /home/$VPS_USER/nextjs_fe.tar.gz
          # xoá các file đã giải nén trong folder nextjs_fe
          rm -rf /home/root/nextjs_fe
        EOF
