name: Deploy to VPS Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy to VPS
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
          cd /home/$VPS_USER || { echo "Failed to access directory /home/$VPS_USER"; exit 1; }
          # Clone the latest version of the repository
          git clone https://github.com/khoidang2110/cicd_vps_docker.git nextjs_fe || (cd nextjs_fe && git pull) || { echo "Failed to clone or pull repository"; exit 1; }
          cd nextjs_fe || { echo "Failed to enter nextjs_fe directory"; exit 1; }
          # Stop and remove the existing container, if any
          docker stop nextjs_fe_container || { echo "Failed to stop container"; } || true
          docker rm nextjs_fe_container || { echo "Failed to remove container"; } || true
          # Remove the old Docker image
          docker rmi -f nextjs_fe_img || { echo "Failed to remove Docker image"; exit 1; } || true
          # Build the Docker image
          docker build -t nextjs_fe_img . || { echo "Failed to build Docker image"; exit 1; }
          # Run the Docker container
          docker run --restart=always -d -p 4000:3000 --name nextjs_fe_container nextjs_fe_img || { echo "Failed to run Docker container"; exit 1; }
          # Clean up by removing the cloned repository files
          cd .. || { echo "Failed to navigate back from nextjs_fe"; exit 1; }
          rm -rf nextjs_fe || { echo "Failed to remove nextjs_fe directory"; exit 1; }
        EOF
